//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {

        public int Id { get; set; }
        [Display(Name = "ชื่อผู้ใช้ :")]
        public string userName { get; set; }
        [Display(Name = "รหัสผ่าน :")]
        public string password { get; set; }
        public Nullable<int> role { get; set; }

        public virtual Role Role1 { get; set; }
    }
}
