//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        public int estimate_Id { get; set; }
        public string status { get; set; }
        public string des { get; set; }
        public string rate { get; set; }
    }
}
