//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renter
    {
        public int renter_Id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public int room_Id { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
