//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Renter
    {
        public int renter_Id { get; set; }
        [Display(name="ชื่อ :")]
        public string name { get; set; }
        [Display(name = "เบอร์โทรศํพท์ :")]
        public string phone { get; set; }
        [Display(name = "ที่อยู่ :")]
        public string address { get; set; }
        [Display(name = "เลขห้อง :")]
        public int room_Id { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
