//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Technician
    {
        public int technician_Id { get; set; }

        [Display(Name = "ชือช่าง :")]
        public string technicianName { get; set; }

        [Display(Name = "ช่างประเภท :")]
        public string typeRepair { get; set; }
        [Display(Name = "เบอร์โทรศัพท์ :")]
        public string phone { get; set; }
        [Display(Name = "รูปโปรไฟล์ :")]
        public string image { get; set; }

    }
}
